-- Reference: <https://aws.amazon.com/ko/blogs/tech/building-a-job-search-engine-with-postgresqls-advanced-search-features/>
--
-- tsvector, tsquery for FTS
-- pgvector for vector search
-- PostGIS for geospatial data

CREATE EXTENSION vector;
CREATE EXTENSION pg_trgm;
CREATE EXTENSION postgis;


CREATE TABLE job (
    job_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company TEXT,
    title TEXT NOT NULL,
    description TEXT,
    title_tsv TSVECTOR  -- Computed full-text search vectors
        GENERATED ALWAYS AS (to_tsvector('english', title)) STORED,
    description_tsv TSVECTOR
        GENERATED ALWAYS AS (to_tsvector('english', description)) STORED,
    semantic_vector VECTOR(3)  
        GENERATED ALWAYS AS (
          embedding_function(title || ' ' || description) -- replace with actual embedding generation
        ) STORED,
    skills_vector VECTOR(3)   -- Computed skills vector
        GENERATED ALWAYS AS (
          embedding_function(array_to_string(skills, ' '))
        ) STORED, 
    geom GEOMETRY(Point, 4326),
    location TEXT,
    salary_range INT4RANGE,
    experience_level TEXT,
    job_location GEOMETRY(Point, 4326),
    skills TEXT[]
);


CREATE TABLE resume (
    candidate_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_name TEXT,
    raw_resume TEXT,
    resume_tsv TSVECTOR  -- Computed search vectors
        GENERATED ALWAYS AS (to_tsvector('english', raw_resume)) STORED,
    skills_vector VECTOR(3)   -- Computed semantic and skills vectors
        GENERATED ALWAYS AS (
         --   embedding_function(array_to_string(skills, ' '))
        ) STORED, 
    geom GEOMETRY(Point, 4326),
    location TEXT,
    skills TEXT[],
    job_history TEXT[],
    education_levels TEXT[]
);


-- Search for resumes with specific skills using full-text search
-- in this example, we are looking for candidates with skills in 'javascript', 'react', or 'angular' but not 'wordpress'
WITH resume AS(SELECT * FROM (VALUES
  ('John','react,javascript, wordpress'),
  ('Mary','angular, javascript')
) resume(candidate_name, skills))
SELECT candidate_name 
FROM resume 
WHERE TO_TSVECTOR(resume.skills) @@ to_tsquery('english', 'javascript & (react | angular) & !wordpress');


-- Search for resumes where ranking is based on the occurrence of the word 'Amazon'
WITH resume AS(
    SELECT * FROM (
        VALUES ('some-company:software engineering'), ('Amazon: software engineering')
    ) resume(skills)
)
SELECT resume.skills, TS_RANK_CD(TO_TSVECTOR(resume.skills), TO_TSQUERY('Amazon')) AS rank 
FROM resume 
ORDER BY rank DESC;



-- Create a function to generate weighted search vector
-- This function assigns weight "A" to column "title", and weight "B" to column "skills" 
CREATE FUNCTION job_search_vector(title TEXT, skills TEXT)
RETURNS tsvector AS $$ 
BEGIN
    RETURN setweight(to_tsvector('english', title), 'A') || setweight(to_tsvector('english', skills), 'B');
END 
$$ LANGUAGE plpgsql;

-- Search for jobs with specific skills using the custom function
WITH job AS(SELECT * FROM (VALUES
  (1,'programmer','java, python, junit'),
  (2,'QA','python, junit')
) job(id,title, skills))
SELECT
    job.id, job.title, job.skills, 
    ts_rank(job_search_vector(job.title, job.skills),
    to_tsquery('QA & python & junit & java')) AS rank 
FROM job 
ORDER BY rank DESC;


-- 
-- Fuzzy search
-- 

SET pg_trgm.similarity_threshold = 0.4;
WITH job AS(
    SELECT * FROM (
        VALUES (1,' programmer','java, python, junit'), (2,'QA','python, junit') 
    ) job(id,title, skills)
)
SELECT * FROM job WHERE job.title % 'programer';


-- 
-- Calculate similarity between job description and resume
-- 
SELECT * FROM (
    WITH job AS(SELECT * FROM (VALUES 
        (1, 'Data Scientist', 'python, machine learning, sql, statistics, deep learning', '[0.9, 0.7, 0.2]'::vector(3)),
        (2, 'Frontend Developer', 'javascript, react, css, html, redux', '[0.2, 0.1, 0.9]'::vector(3)),
        (3, 'Backend Engineer', 'java, spring, microservices, sql, api design', '[0.5, 0.9, 0.3]'::vector(3)),
        (4, 'DevOps Engineer', 'kubernetes, docker, aws, terraform, ci/cd', '[0.6, 0.8, 0.4]'::vector(3))
    ) job(job_id, title, skills, skill_vector)
    ),
    resume AS(SELECT * FROM (VALUES 
        (1, 'Mary', 'java, spring boot, microservices, postgresql, rest api', '[0.45, 0.95, 0.25]'::vector(3)),
        (2, 'Jean', 'docker, kubernetes, aws, jenkins, terraform', '[0.65, 0.75, 0.35]'::vector(3)),
        (3, 'Bill', 'javascript, python, react, express, mongodb, node.js', '[0.35, 0.6, 0.65]'::vector(3))
    ) resume(candidate_id, name, skills, skill_vector)
    )
    SELECT job.title, resume.name, 
           1 - (job.skill_vector  resume.skill_vector) AS similarity_score -- Cosine similarity from distance
    FROM job CROSS JOIN resume
) scores 
WHERE similarity_score > 0.9
ORDER BY similarity_score DESC;


-- 
-- Add indexes for vector search
-- 

-- 1. IVFFlat for large datasets (partitioning the vector space)
CREATE INDEX ON resume USING ivfflat (skills_vector vector_l2_ops) WITH (lists = 100);

-- 2. HNSW for graph-based high precision search
CREATE INDEX ON resume USING hnsw (skills_vector vector_cosine_ops) WITH (m=16, ef_construction=64);


-- 
-- PostGIS for geospatial data
-- 

ALTER TABLE job ADD COLUMN location GEOMETRY(Point, 4326);
ALTER TABLE resume ADD COLUMN location GEOMETRY(Point, 4326);

CREATE INDEX job_location_idx ON job USING GIST (location);
CREATE INDEX resume_location_idx ON resume USING GIST (location);


WITH job AS (SELECT * FROM (VALUES
        (1, 'Data Scientist', 'python, machine learning, sql, statistics, deep learning', ST_SetSRID(ST_MakePoint(-122.4194, 37.7749), 4326)), -- San Francisco
        (2, 'Frontend Developer', 'javascript, react, css, html, redux', ST_SetSRID(ST_MakePoint(-74.0060, 40.7128), 4326)), -- New York
        (3, 'Backend Engineer', 'java, spring, microservices, sql, api design', ST_SetSRID(ST_MakePoint(-118.2437, 34.0522), 4326)) -- Los Angeles
    ) job(job_id, title, skills, location)
),
resume AS( SELECT * FROM (VALUES
        (1, 'John ', 'python, machine learning, tensorflow, statistics, pandas', ST_SetSRID(ST_MakePoint(-122.3321, 37.8272), 4326)), -- Berkeley 
        (3, 'Mary', 'java, spring boot, microservices, postgresql, rest api', ST_SetSRID(ST_MakePoint(-118.4912, 34.0195), 4326)), -- Santa Monica 
        (10, 'Riley', 'javascript, python, node.js, react, graphql, mongodb', ST_SetSRID(ST_MakePoint(-84.3880, 33.7490), 4326)) -- Atlanta 
    ) resume(candidate_id, name, skills, location)
),
-- Calculate distances and rank candidates by proximity
ranked_candidates AS (
    SELECT j.title AS job_title,
        CASE j.job_id 
            WHEN 1 THEN 'San Francisco'
            WHEN 2 THEN 'New York'
            WHEN 3 THEN 'Los Angeles'
            WHEN 4 THEN 'Chicago'
            WHEN 5 THEN 'Dallas'
        END AS job_location, 
        r.name AS candidate_name,
        -- Calculate distance in kilometers
        ST_Distance(j.location::geography, r.location::geography) / 1000 AS distance_km,
        -- Rank candidates for each job by distance
        ROW_NUMBER() OVER (PARTITION BY j.job_id ORDER BY ST_Distance(j.location::geography, r.location::geography)) AS rank 
    FROM job j 
    CROSS JOIN resume r 
)
-- Select only the closest candidate for each job
SELECT job_title, job_location, candidate_name, ROUND(distance_km::numeric, 1) AS distance_km,
    CASE -- Provide context about the proximity
        WHEN distance_km < 5 THEN 'Walking distance'
        WHEN distance_km < 15 THEN 'Short commute'
        WHEN distance_km < 30 THEN 'Moderate commute'
        ELSE 'Remote work only'
    END AS commute_assessment 
FROM ranked_candidates 
WHERE TO_TSVECTOR ('english', job_title) @@ TO_TSQUERY ('english', 'engineer') -- select engineers only
AND rank = 1
ORDER BY job_title;


-- Complex hybrid search combining full-text, vector, and geospatial
WITH job AS (SELECT * FROM (VALUES
        (1, 'Data Scientist', 'python, machine learning, sql, statistics, deep learning',
         '[0.9, 0.7, 0.2]'::vector(3), 
         ST_SetSRID(ST_MakePoint(-122.4194, 37.7749), 4326)), -- San Francisco
        (2, 'Frontend Developer', 'javascript, react, css, html, redux',
         '[0.2, 0.1, 0.9]'::vector(3), 
         ST_SetSRID(ST_MakePoint(-74.0060, 40.7128), 4326)), -- New York
        (3, 'Backend Engineer', 'java, spring, microservices, sql, api design',
         '[0.5, 0.9, 0.3]'::vector(3), 
         ST_SetSRID(ST_MakePoint(-118.2437, 34.0522), 4326)), -- Los Angeles
        (4, 'DevOps Engineer', 'kubernetes, docker, aws, terraform, ci/cd',
         '[0.6, 0.8, 0.4]'::vector(3), 
         ST_SetSRID(ST_MakePoint(-87.6298, 41.8781), 4326)), -- Chicago
        (5, 'Full Stack Developer', 'javascript, python, react, node.js, mongodb',
         '[0.4, 0.5, 0.7]'::vector(3), 
         ST_SetSRID(ST_MakePoint(-96.7970, 32.7767), 4326)) -- Dallas
    ) job(job_id, title, skills, skill_vector, location)
), 
resume AS(SELECT * FROM (VALUES
        (1, 'John', 'python, machine learning, tensorflow, statistics, pandas', '[0.85, 0.6, 0.25]'::vector(3), 
         ST_SetSRID(ST_MakePoint(-122.3321, 37.8272), 4326)), -- Berkeley (near SF)
        (2, 'Sam', 'javascript, react, css, html, typescript, sass', '[0.15, 0.2, 0.95]'::vector(3), 
         ST_SetSRID(ST_MakePoint(-73.9352, 40.7306), 4326)), -- Queens, NY
        (3, 'Mary', 'java, spring boot, microservices, postgresql, rest api', '[0.45, 0.95, 0.25]'::vector(3), 
         ST_SetSRID(ST_MakePoint(-118.4912, 34.0195), 4326)), -- Santa Monica (near LA)
        (4, 'Jean', 'docker, kubernetes, aws, jenkins, terraform', '[0.65, 0.75, 0.35]'::vector(3), 
         ST_SetSRID(ST_MakePoint(-87.9065, 41.9742), 4326)), -- Evanston (near Chicago)
        (5, 'Bill', 'javascript, python, react, express, mongodb, node.js', '[0.35, 0.6, 0.65]'::vector(3), 
         ST_SetSRID(ST_MakePoint(-84.3880, 33.7490), 4326)) -- Atlanta (far from Dallas)
    ) resume(candidate_id, name, skills, skill_vector, location)
), 
all_matches AS ( -- Calculate all matches with scores
    SELECT job.job_id, job.title AS job_title, job.skills AS job_skills, resume.candidate_id, resume.name AS candidate_name, resume.skills AS candidate_skills, 
        cosine_similarity(job.skill_vector, resume.skill_vector) AS skill_similarity, 
        ST_Distance(job.location::geography, resume.location::geography) / 1000 AS distance_km,
        -- Location score (inversely related to distance) 
        GREATEST(0, 1 - (ST_Distance(job.location::geography, resume.location::geography) / 1000 / 500)) AS location_score,
        (cosine_similarity(job.skill_vector, resume.skill_vector) * 0.7) + -- Combined score (70% skill, 30% location)
        (GREATEST(0, 1 - (ST_Distance(job.location::geography, resume.location::geography) / 1000 / 500)) * 0.3) AS combined_score 
    FROM job CROSS JOIN resume 
), 
ranked_matches AS ( -- Rank candidates for each job
    SELECT job_id, job_title, job_skills, candidate_id, candidate_name, candidate_skills, skill_similarity, distance_km, location_score, combined_score,
        -- Rank within each job_id group by combined score 
        ROW_NUMBER() OVER (PARTITION BY job_id ORDER BY combined_score DESC) AS rank 
    FROM all_matches 
)
SELECT job_title, candidate_name,
    ROUND(skill_similarity::numeric, 2) AS skill_score, ROUND(distance_km::numeric, 1) AS distance_km,
    ROUND(location_score::numeric, 2) AS location_score, ROUND(combined_score::numeric, 2) AS combined_score,
    CASE -- Detailed match assessment
        WHEN skill_similarity >= 0.9 AND distance_km = 0.8 AND distance_km = 0.7 AND distance_km = 0.6 OR distance_km <= 300 THEN 'Potential Match'
        ELSE 'Low Match'
    END AS match_quality 
FROM ranked_matches 
WHERE TO_TSVECTOR ('english', job_title) @@ TO_TSQUERY ('english', 'engineer')
AND rank = 1 
ORDER BY job_id;
